- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.670'
  hooks:
    - id: mypy
      exclude: bin/storas
- repo: https://github.com/pre-commit/mirrors-pylint
  rev: 'v2.3.1'
  hooks:
    - id: pylint
      exclude: bin/storas
